tasks:
  - name: Boot
    init: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
    command: docker compose up
  - name: Readme
    command: code README.md
    openMode: tab-after


# Exposed services:
ports:
  - name: Hasura APIs
    description: Runs the Hasura Engine APIs
    port: 5000
    visibility: public
    onOpen: ignore
  - name: Hasura CLI APIs
    description: Runs the Hasura CLI APIs
    port: 9693
    visibility: public
    onOpen: ignore
  - name: Hasura Console
    description: Runs the Hasura Web Console
    port: 9695
    visibility: public
    onOpen: open-preview
  - name: Adminer
    description: Runs Adminer database Web Client
    port: 8081
    visibility: public
    onOpen: ignore
  - name: Postgres
    port: 5432
    onOpen: ignore
    
vscode:
  extensions:
    - Codeium.codeium
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - darkriszty.markdown-table-prettify
